CREATE TABLE `data_set_detail_areas` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`reference_date` text NOT NULL,
	`address` text,
	`young_population_ratio` real,
	`elderly_population_ratio` real,
	`total_building_count` integer,
	`vacant_house_ratio` real,
	`area` real,
	`geometry` text,
	`key_code` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `data_set_detail_buildings` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`household_code` text,
	`normalized_address` text,
	`reference_date` text NOT NULL,
	`household_size` integer,
	`members_under_15` integer,
	`percentage_under_15` real,
	`members_15_to_64` integer,
	`percentage_15_to_64` real,
	`members_over_65` integer,
	`percentage_over_65` real,
	`gender_ratio` real,
	`residence_duration` integer,
	`water_supply_number` text,
	`water_disconnection_flag` integer,
	`max_water_usage` real,
	`avg_water_usage` real,
	`total_water_usage` real,
	`min_water_usage` real,
	`water_supply_source_info` text,
	`structure_name` text,
	`registration_date` text,
	`registration_source_info` text,
	`vacant_house_id` text,
	`vacant_house_address` text,
	`vacant_house_longitude` real,
	`vacant_house_latitude` real,
	`vacant_house_source_info` text,
	`geocoded_address` text,
	`geocoded_longitude` real,
	`geocoded_latitude` real,
	`geocoding_source_info` text,
	`has_water_supply` integer,
	`has_juki_registry` integer,
	`has_touki_registry` integer,
	`has_juki_and_water` integer,
	`has_vacant_result` integer,
	`has_juki_water_property` integer,
	`has_geocoding` integer,
	`has_juki_water_property_vacant` integer,
	`fid` text,
	`gml_id` text,
	`class` text,
	`geometry` text,
	`measuredheight` real,
	`measuredheight_uom` real,
	`src_scale` text,
	`geometry_src_desc` text,
	`thematic_src_desc` text,
	`lod1_height_type` text,
	`building_id` text,
	`prefecture` text,
	`city` text,
	`description` text,
	`rank` integer,
	`depth` integer,
	`depth_uom` text,
	`admin_type` text,
	`scale` text,
	`duration` real,
	`duration_uom` text,
	`building_use` text,
	`floors_above_ground` integer,
	`floors_below_ground` integer,
	`value` real,
	`value_uom` text,
	`inland_flooding_risk_desc` text,
	`inland_flooding_risk_rank` integer,
	`inland_flooding_risk_depth` real,
	`inland_flooding_risk_depth_uom` text,
	`river_flooding_risk_desc` text,
	`river_flooding_risk_rank` integer,
	`river_flooding_risk_depth` real,
	`river_flooding_risk_depth_uom` text,
	`landslide_risk_desc` text,
	`large_store_name` text,
	`appearance_src_desc` text,
	`branch_id` text,
	`residence_id` text,
	`is_test` integer,
	`name` text,
	`area_type` text,
	`predicted_label` integer,
	`predicted_probability` real,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);