CREATE TABLE `data_set_detail_areas` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `data_set_detail_buildings` (
	`id` integer PRIMARY KEY NOT NULL,
	`data_set_result_id` integer,
	`household_code` text,
	`normalized_address` text,
	`reference_date` text NOT NULL,
	`number_of_people_in_household` integer,
	`number_of_people_under_15_years_old` integer,
	`composition_ratio_of_people_under_15_years_old` real,
	`number_of_people_aged_15_to_64` integer,
	`composition_ratio_of_people_aged_15_to_64` real,
	`number_of_people_aged_65_and_over` integer,
	`composition_ratio_of_people_aged_65_and_over` real,
	`male_to_female_ratio` real,
	`period_of_residence` integer,
	`water_number_suido_residence` text,
	`closing_flag_suido_residence` integer,
	`maximum_water_usage_suido_residence` real,
	`average_water_usage_suido_residence` real,
	`total_water_usage_suido_residence` real,
	`minimum_water_usage_suido_residence` real,
	`name_source_information_suido_residence` text,
	`structure_name_touki_residence` text,
	`registration_date_touki_residence` text,
	`name_source_information_touki_residence` text,
	`id_akiya_result_cleaned` text,
	`address_akiya_result_cleaned` text,
	`geometry` text,
	`measuredheight` real,
	`rank` integer,
	`depth` integer,
	`duration` real,
	`number_of_floors_above_ground` integer,
	`number_of_basement_floors` integer,
	`buildingdisasterriskattribute_buildinginlandfloodingriskattribute_description` text,
	`buildingdisasterriskattribute_buildinginlandfloodingriskattribute_rank` integer,
	`buildingdisasterriskattribute_buildinginlandfloodingriskattribute_depth` real,
	`buildingdisasterriskattribute_buildingriverfloodingriskattribute_description` text,
	`buildingdisasterriskattribute_buildingriverfloodingriskattribute_rank` integer,
	`buildingdisasterriskattribute_buildingriverfloodingriskattribute_depth` real,
	`buildingdisasterriskattribute_buildinglandslideriskattribute_description` text,
	`name` text,
	`pred` integer,
	`pred_proba` real,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
