export type data_set_detail_buildings = {
  household_id: string;
  residence_id: string;
  number_of_people_in_household: number;
  number_of_people_under_15_years_old: number;
  composition_ratio_of_people_under_15_years_old: number;
  number_of_people_aged_15_to_64: number;
  composition_ratio_of_people_aged_15_to_64: number;
  number_of_people_aged_65_and_over: number;
  composition_ratio_of_people_aged_65_and_over: number;
  gender_ratio: number;
  period_of_residence: number;
  closing_flag_suido_residence: boolean;
  maximum_water_usage_suido_residence: number;
  structure_name_touki_residence: string;
  registration_date_touki_residence: Date;
  akiya_result_cleaned_flag: boolean;
  geometry: any;
  predicted_label: string;
  predicted_probability: number;
};
