name: Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and package
        run: npm run make

      - name: Rename file for macOS
        if: matrix.os == 'macos-latest'
        run: |
          mv out/make/zip/darwin/arm64/links-akiya-darwin-arm64-0.0.0.zip out/links-akiya-macos.zip

      - name: Rename file for Windows
        if: matrix.os == 'windows-latest'
        run: |
          $foundFile = Get-ChildItem -Path "out/make/zip/win32" -Filter "*.zip" -Recurse
          if ($foundFile) {
              Write-Output "File found at: $($foundFile.FullName)"
          } else {
              Write-Error "File not found"
          }
      #     mv out/links-akiya-win32-x64/links-akiya.zip out/links-akiya-windows.zip

      # - name: Release Electron app for macOS
      #   if: matrix.os == 'macos-latest'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v0.0.${{ github.run_number }}
      #     draft: false
      #     prerelease: false
      #     files: |
      #       out/links-akiya-macos.zip

      # - name: Release Electron app for Windows
      #   if: matrix.os == 'windows-latest'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v0.0.${{ github.run_number }}
      #     draft: false
      #     prerelease: false
      #     files: |
      #       out/links-akiya-windows.exe
