name: Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and package
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            out/make/zip/darwin/arm64/*.zip
            out/make/zip/linux/arm64/*.zip
            out/make/zip/win32/arm64/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./artifacts/out/make/zip/darwin/arm64/*.zip
            ./artifacts/out/make/zip/linux/arm64/*.zip
            ./artifacts/out/make/zip/win32/arm64/*.zip
          tag_name: "v0.0.${{ github.run_number }}"
          draft: false
          prerelease: false
